name: Optipy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  optipy:
    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: 1
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run optipy
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      run: |      
        DISABLE_OPTIMIZATION=true

        if [ "$DISABLE_OPTIMIZATION" = true ]; then
          echo "Optimization process is disabled"
          exit 0
        fi

        EXCLUDE_PATTERNS=(
          "./optipy.py"
          "./toolbox.py"
          "./case_studies/*"
        )

        for file in $(find . -name "*.py"); do
          SKIP=false
          for pattern in "${EXCLUDE_PATTERNS[@]}"; do
            if [[ "$file" == $pattern ]]; then
              echo "Skipping $file (matched pattern $pattern)"
              SKIP=true
              break
            fi
          done
          
          if [ "$SKIP" = false ]; then
            echo "Processing $file"
            python optipy.py --filepath="$file" --model=gpt-4o --strategy=one_by_one --debug
          fi
        done
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Apply optipy changes"
          git push
        fi